--Task#01:

SELECT E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_ID;

--Task 02:

SELECT COUNT(E.EMPLOYEE_ID) NO_OF_EMPLOYEES, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID)>=2;

--Task 03:

SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.JOB_ID
FROM EMPLOYEES E1, JOBS J
WHERE E1.JOB_ID = J.JOB_ID AND E1.SALARY < J.MIN_SALARY;

--Task 04:

SELECT E.FIRST_NAME, E.LAST_NAME, E.JOB_ID, J.JOB_TITLE, E.SALARY * 12 "ANNUAL_SALARY", E.DEPARTMENT_ID, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND E.JOB_ID= J.JOB_ID
AND ((E.SALARY*12) = 60000 OR J.JOB_TITLE != 'Analyst');

--Task 05:

SELECT DISTINCT E1.EMPLOYEE_ID, E1.FIRST_NAME, E1.LAST_NAME, E1.JOB_ID, E1.DEPARTMENT_ID
FROM EMPLOYEES E1, EMPLOYEES E2 WHERE E2.MANAGER_ID = E1.EMPLOYEE_ID;


--Task 06:

SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID= D.DEPARTMENT_ID
GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID)=0;

--Task 07:

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "EMPLOYEE NAME", E.SALARY, D.DEPARTMENT_NAME 
FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--Task 8:

SELECT E.FIRST_NAME, E.JOB_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME, L.STREET_ADDRESS, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID
AND L.STATE_PROVINCE IS NULL;

--Task 9:
SELECT LOCATION_ID FROM DEPARTMENTS MINUS SELECT LOCATION_ID FROM LOCATIONS;


--Task 10:

SELECT E.FIRST_NAME, E.LAST_NAME, L.STATE_PROVINCE, L.COUNTRY_ID
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID
AND L.COUNTRY_ID = 'US' AND L.STATE_PROVINCE != 'Washington';